flags:
  vector:
    unsafechecks: true
    internalchecks: true
extra-package-dbs: []
packages:
- '.'
extra-deps:
- daemons-0.2.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- liquid-fixpoint-0.5.0.1
- liquidhaskell-0.6.0.0
- located-base-0.1.1.0
- vector-0.11.0.0
resolver: lts-6.7
